#define ERR_VFS_CREATE_01 printf("DATA_FILE_ALREADY_EXISTS\n");
#define ERR_VFS_CREATE_02 printf("CANNOT_CREATE_DATAFILE\n");
#define ERR_VFS_CREATE_03 printf("NOT_ENOUGH_MEMORY\n");
#define ERR_VFS_CREATE_04 printf("INVALID_CHARACTER_IN_NAME\n");
#define ERR_VFS_CREATE_05 printf("INVALID_SIZE\n");

#define ERR_VFS_MOUNT_01 printf("DATA_FILE_NOT_FOUND\n");
#define ERR_VFS_MOUNT_02 printf("CANNOT_READ_FROM_FILE\n");
#define ERR_VFS_MOUNT_03 printf("INVALID_HEADER\n");

#define ERR_VFS_UNMOUNT_01 printf("DATA_FILE_NOT_FOUND\n");
#define ERR_VFS_UNMOUNT_02 printf("ACCESS_DENIED\n");
#define ERR_VFS_UNMOUNT_03 printf("CANNOT_WRITE_TO_FILE\n");

#define ERR_VFS_MAKEDIR_01 printf("UNABLE_TO_CREATE_NEWDIR\n");
#define ERR_VFS_MAKEDIR_02 printf("INVALID_CHARACTER_IN_DIRNAME\n");
#define ERR_VFS_MAKEDIR_03 printf("DIRECTORY_ALREADY_EXISTS\n");

#define ERR_VFS_DELETEDIR_01 printf("CANNOT_FIND_SPECIFIED_PATH_OR_DIR\n");
#define ERR_VFS_DELETEDIR_02 printf("DIRECTORY_IS_NOT_EMPTY\n");
#define ERR_VFS_DELETEDIR_03 printf("INVALID_DIRNAME\n");

#define ERR_VFS_MOVEDIR_01 printf("CANNOT_FIND_SPECIFIED_SOURCEDIR\n");
#define ERR_VFS_MOVEDIR_02 printf("CANNOT_FIND_SPECIFIED_DESTINATIONDIR\n");
#define ERR_VFS_MOVEDIR_03 printf("SOURCE_PATH_MISSING\n");
#define ERR_VFS_MOVEDIR_04 printf("DESTINATION_PATH_MISSING\n");
#define ERR_VFS_MOVEDIR_05 printf("DESTINATION_ALREADY_HAVE_SOURCE_DIR\n");

#define ERR_VFS_LISTDIR_01 printf("CANNOT_FIND_SPECIFIED_PATH_OR_DIR\n");
#define ERR_VFS_LISTDIR_02 printf("INVALID_FLAG\n");
#define ERR_VFS_LISTDIR_03 printf("CANNOT_FIND_OUTPUTFILE\n");

#define ERR_VFS_ADDFILE_01 printf("UNABLE_TO_CREATE_NEWFILE\n");
#define ERR_VFS_ADDFILE_02 printf("INVALID_CHARACTER_IN_FILENAME\n");
#define ERR_VFS_ADDFILE_03 printf("FILE_ALREADY_EXISTS\n");
#define ERR_VFS_ADDFILE_04 printf("FILE_SYSTEM_FULL\n");

#define ERR_VFS_LISTFILE_01 printf("SOURCE_FILE_PATH_NOT_FOUND\n");
#define ERR_VFS_LISTFILE_02 printf("OUTPUT_FILE_PATH_NOT_FOUND\n");
#define ERR_VFS_LISTFILE_03 printf("SOURCE_PATH_MISSING\n");
#define ERR_VFS_LISTFILE_04 printf("OUTPUT_PATH_MISSING\n");
#define ERR_VFS_LISTFILE_05 printf("NOT_A_TEXT_FILE\n");

#define ERR_VFS_UPDATEFILE_01 printf("SOURCE_FILE_PATH_NOT_FOUND\n");
#define ERR_VFS_UPDATEFILE_02 printf("DEST_FILE_PATH_NOT_FOUND\n");
#define ERR_VFS_UPDATEFILE_03 printf("INCORRECT_FILE_FORMAT\n");
#define ERR_VFS_UPDATEFILE_04 printf("FILE_SYSTEM_FULL\n");

#define ERR_VFS_REMOVEFILE_01 printf("CANNOT_FIND_SPECIFIED_PATH_OR_FILE\n");

#define ERR_VFS_MOVEFILE_01 printf("CANNOT_FIND_SPECIFIED_SOURCEFILE\n");
#define ERR_VFS_MOVEFILE_02 printf("CANNOT_FIND_SPECIFIED_DESTINATIONFILE\n");
#define ERR_VFS_MOVEFILE_03 printf("SOURCE_PATH_MISSING\n");
#define ERR_VFS_MOVEFILE_04 printf("DESTINATION_PATH_MISSING\n");

#define ERR_VFS_COPYFILE_01 printf("CANNOT_FIND_SPECIFIED_SOURCEFILE\n");
#define ERR_VFS_COPYFILE_02 printf("CANNOT_FIND_SPECIFIED_DESTINATIONFILE\n");
#define ERR_VFS_COPYFILE_03 printf("SOURCE_PATH_MISSING\n");
#define ERR_VFS_COPYFILE_04 printf("DESTINATION_PATH_MISSING\n");
#define ERR_VFS_COPYFILE_05 printf("CANNOT_COPY_DIR_TO_FILE\n");
#define ERR_VFS_COPYFILE_06 printf("FILE_SYSTEM_FULL\n");

#define ERR_VFS_EXPORTFILE_00 printf("VFS_INSUFFICIENT_ARGUMENTS\n");
#define ERR_VFS_EXPORTFILE_01 printf("CANNOT_FIND_SOURCEFILE\n");
#define ERR_VFS_EXPORTFILE_02 printf("CANNOT_CREATE_OUTPUTFILE\n");
#define ERR_VFS_EXPORTFILE_03 printf("CANNOT_EXPORT_DIR\n");
#define ERR_VFS_EXPORTFILE_04 printf("VFS_NOT_MOUNTED\n");
#define ERR_VFS_EXPORTFILE_05 printf("OUTPUT_FILE_ALREADY_EXISTS\n");
#define ERR_VFS_EXPORTFILE_06 printf("CANNOT_EXPORT_DIR\n");

#define ERR_VFS_SEARCHFILE_00 printf("VFS_INSUFFICIENT_ARGUMENTS\n");
#define ERR_VFS_SEARCHFILE_02 printf("VFS_NOT_MOUNTED\n");
